version: '2'
services:

  postgres:
    ports:
      - "5432:5432"
    env_file: 
      - ./postgres/postgres.env       

  mariadb:
    ports:
      - "3306:3306"
    env_file: 
      - ./mariadb/mariadb.env      

  odoo:
    ports:
      - "8069:8069"

  nginx:
    env_file: 
      - ./nginx/nginx.priv.env
    build:
      dockerfile: Dockerfile-dev     
      
  redmine-legacy:
    env_file: 
      - common.priv.env    
      - ./redmine-legacy/redmine.env

  redmine:
    env_file: 
      - common.priv.env    
      - ./redmine/redmine.env        
  xibo:
    env_file: 
      - common.priv.env
      - ./xibo/xibo.env

  booked:
    env_file: 
      - common.priv.env    
      - ./booked/booked.env

  osticket:
    env_file:
      - ./osticket/osticket.priv.env

  jenkins:
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins/php.dev.ini:/usr/local/etc/php/php.ini      
      - ./jenkins/php.dev-noxdebug.ini:/usr/local/etc/php/php-noxdebug.ini             
