version: '2'
services:

  mariadb:
    env_file: /etc/docker/mariadb.env

  nginx:
    env_file:
      - /etc/docker/common.env
      - /etc/docker/nginx.env
    build:
      dockerfile: Dockerfile-prod

  redmine:
    env_file:
      - /etc/docker/common.env
      - /etc/docker/redmine.env
    logging:
      driver: syslog
      options:
        syslog-address: udp://localhost:514
        tag: redmine
  xibo:
    env_file:
      - /etc/docker/common.env
      - /etc/docker/xibo.env

  osticket:
    env_file:
      - /etc/docker/common.env
      - /etc/docker/osticket.env
