version: '2'
services:

  postgres:
    ports:
      - "5432:5432"
    env_file: 
      - ./postgres/postgres.env       

  mariadb:
    ports:
      - "3306:3306"
    env_file: 
      - ./mariadb/mariadb.env      

  odoo:
    ports:
      - "8069:8069"

  nginx:
    env_file: 
      - ./nginx/nginx.priv.env
    build:
      dockerfile: Dockerfile-dev      

  redmine:
    env_file: 
      - common.priv.env    
      - ./redmine/redmine.env  

  xibo:
    env_file: 
      - common.priv.env
      - ./xibo/xibo.env

  booked:
    env_file: 
      - common.priv.env    
      - ./booked/booked.env

  osticket:
    environment:
      - MYSQL_PASSWORD=secret
      - MYSQL_USER=root
