version: '2'

networks:
  front:
    external: true
  back:
    external: true

services:
  glpi:
    container_name: glpi
    build: .
    networks:
      - front
      - back
    ports:
      - "8080:80"
    env_file:
      - ./glpi.priv.env
