FROM nginx:stable
MAINTAINER Mikael Kermorgant <mikael.kermorgant@gmail.com>
ENV REFRESHED_AT 2016-05-20

RUN mkdir -p /var/www/html
RUN rm -f /etc/nginx/conf.d/*

COPY nginx.conf /etc/nginx/nginx.conf
COPY conf-prod.d/odoo.conf /etc/nginx/conf.d/odoo.conf
COPY conf-prod.d/redmine-legacy.conf /etc/nginx/conf.d/redmine-legacy.conf
COPY conf-prod.d/redmine.conf /etc/nginx/conf.d/redmine.conf
COPY conf-prod.d/ds.conf /etc/nginx/conf.d/ds.conf
COPY conf-prod.d/jenkins.conf /etc/nginx/conf.d/jenkins.conf
COPY conf-prod.d/local.conf /etc/nginx/conf.d/local.conf
COPY conf-prod.d/osticket.conf /etc/nginx/conf.d/osticket.conf
COPY conf-prod.d/htpasswd /etc/nginx/.htpasswd
COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh /usr/local/bin/wait-for-it.sh
RUN ln -sf /proc/1/fd/1 /var/log/nginx/access.log
RUN ln -sf /proc/1/fd/2 /var/log/nginx/error.log

RUN touch /INSTALL-FLAG

ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
