FROM nginx:stable
MAINTAINER Mikael Kermorgant <mikael.kermorgant@gmail.com>
ENV REFRESHED_AT 2016-05-20

RUN mkdir -p /var/www/html

COPY nginx.conf /etc/nginx/nginx.conf
COPY conf-prod.d/global.conf /etc/nginx/conf.d/default.conf
COPY conf-prod.d/redmine.conf /etc/nginx/conf.d/redmine.conf
COPY conf-prod.d/ds.conf /etc/nginx/conf.d/ds.conf
COPY conf-prod.d/tunnel.conf /etc/nginx/conf.d/tunnel.conf
COPY conf-prod.d/preview.conf /etc/nginx/conf.d/preview.conf
COPY conf-prod.d/htpasswd /etc/nginx/.htpasswd
COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh /usr/local/bin/wait-for-it.sh
RUN ln -sf /proc/1/fd/1 /var/log/nginx/access.log
RUN ln -sf /proc/1/fd/2 /var/log/nginx/error.log

RUN touch /INSTALL-FLAG

ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
