FROM nginx:stable
MAINTAINER Mikael Kermorgant <mikael.kermorgant@gmail.com>
ENV REFRESHED_AT 2016-05-20

RUN apt-get update
RUN apt-get upgrade -y
RUN mkdir -p /var/www/html

ADD nginx.conf /etc/nginx/nginx.conf
ADD conf-prod.d/global.conf /etc/nginx/conf.d/default.conf
ADD conf-prod.d/redmine.conf /etc/nginx/conf.d/redmine.conf
ADD conf-prod.d/ds.conf /etc/nginx/conf.d/ds.conf
ADD conf-prod.d/tunnel.conf /etc/nginx/conf.d/tunnel.conf
ADD conf-prod.d/preview.conf /etc/nginx/conf.d/preview.conf
ADD conf-prod.d/htpasswd /etc/nginx/.htpasswd

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh  /usr/local/bin/wait-for-it.sh
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh /usr/local/bin/wait-for-it.sh

RUN touch /INSTALL-FLAG

ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
