version: '2'

volumes:
  mariadbstore:
    external: true
  xibodata:
    external: true

networks:
  front:
    external: true
  back:
    external: true

services:
  nginx:
    container_name: nginx
    build: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl:/etc/ssl:ro
      - ./nginx/local:/var/www

      - xibodata:/var/www/xibo:ro
      # - bookeddata:/var/www/booked:ro
      # - osticketdata:/var/www/osticket:ro
    ports:
      - "80:80"
    networks:
      - front
      - back

  nginx-gen:
    container_name: nginx-gen
    image: jwilder/docker-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - nginx
    command: "-notify-sighup nginx -watch /etc/docker-gen/nginx.tmpl /etc/nginx/conf.d/default.conf"
    networks:
      - front

  # haproxy:
  #   image: haproxy:1.6
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  #   networks:
  #     - front

  mariadb:
    container_name: mariadb
    image: mariadb:10.1
    expose:
      - "3306"
    volumes:
      - mariadbstore:/var/lib/mysql
    networks:
      - back

  syslog:
    container_name: syslog
    build: syslog
    networks:
      - back
    ports:
      - "localhost:514:514/udp"
