version: '2'
services:
  mariadb:
    env_file: /etc/docker/mariadb.env
    depends_on:
      - syslog
    logging:
      driver: syslog
      options:
        syslog-address: udp://localhost:514
        tag: mariadb

  nginx:
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf-dev.d/:/etc/nginx/conf.d


  nginx-gen:
    volumes:
      - ./nginx/conf-prod.d/nginx.tmpl:/etc/docker-gen/nginx.tmpl

  # haproxy:
  #   depends_on:
  #     - syslog
  #   logging:
  #     driver: syslog
  #     options:
  #       syslog-address: udp://localhost:514
  #       tag: haproxy
